# data
feeder: feeder.feeder_ntu_semi.Feeder
train_feeder_args:
  data_path: data/ntu/NTU60_XView.npz
  data_ratio: 0.1
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 120
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

val_feeder_args:
  data_path: data/ntu/NTU60_XView.npz
  split: test  
  debug: False
  window_size: 120
  p_interval: [0.95]
  vel: False
  bone: False

# model
model: model.transformer.Transformer
model_args:
  dim_in: 3
  num_classes: 60
  dim_feat: 256
  depth: 8
  num_heads: 8
  mlp_ratio: 4
  num_frames: 120
  num_joints: 25
  patch_size: 1
  t_patch_size: 4
  qkv_bias: True
  qk_scale: None
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.3
  protocol: finetune

# training
epochs: 100
warmup_epochs: 5
batch_size: 24
lr: 5e-4
layer_decay: 0.8
smoothing: 0.1